apiVersion: v1
kind: Service
metadata:
  name: otel-collector
  namespace: telemetry
  labels:
    app.kubernetes.io/name: otel-collector
    app.kubernetes.io/part-of: observability
spec:
  selector:
    app.kubernetes.io/name: otel-collector
  ports:
    - name: otlp-grpc
      port: 4317
      targetPort: otlp-grpc
    - name: otlp-http
      port: 4318
      targetPort: otlp-http
    - name: metrics
      port: 8889
      targetPort: metrics
